auth_enabled: false

server:
  http_listen_port: 3100

ingestion_rate_mb: 10
ingestion_burst_size_mb: 20

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: filesystem
    cache_location: /loki/cache

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 dias de logs

compactor:
  retention_enabled: true
  retention_delete_delay: 24h
  retention_delete_worker_count: 2
