global:
  scrape_interval: 5s  
  
scrape_configs:
  - job_name: 'backend'
    metrics_path: '/metrics'  
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
